name: Wiki Update Notification
on:
  gollum:
    branches:
      - main
jobs:
  slack-notification:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Prepare Slack Message
        id: prepare_message
        run: |
          echo "Generating Slack message..."
          # Use jq to parse and format the pages
          UPDATED_PAGES=$(echo '${{ toJSON(github.event.pages) }}' | jq -r '.[] | "• *\(.title)*\n  Action: \(.action)\n  Page URL: \(.html_url)"')
          
          # Replace newlines with literal '\n' for JSON
          UPDATED_PAGES=$(echo "$UPDATED_PAGES" | sed $'s/\n/\\\\n/g')
          
          echo "UPDATED_PAGES=${UPDATED_PAGES}" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "📝 Wiki Pages Updated",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*The following Wiki pages were updated:*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.prepare_message.outputs.UPDATED_PAGES }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "📍 Repository: ${{ github.repository }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
