name: Wiki Update Notification

on:
  gollum:
    branches:
      - main

jobs:
  slack-notification:
    runs-on: ubuntu-latest  # Changed to ensure compatibility with required tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Slack Message
        id: prepare_message
        run: |
          echo "Preparing Slack message..."
          # Extract the updated pages from the event
          PAGES=$(echo '${{ toJSON(github.event.pages) }}' | jq -r '.[] | "- [\(.title)](\(.html_url))"')
          echo "Updated Pages: $PAGES"
          echo "UPDATED_PAGES=$PAGES" >> $GITHUB_ENV

      - name: Debug Message
        run: |
          echo "DEBUG: $UPDATED_PAGES"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "📝 The following Wiki pages were updated:",
              "attachments": [
                {
                  "title": "Updated Pages",
                  "text": "${{ env.UPDATED_PAGES }}",
                  "color": "#36a64f"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

