name: Wiki Update Notification

on:
  gollum:
    branches:
      - main

jobs:
  slack-notification:
    runs-on: macos-latest  # Platform for running the workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Slack Message
        id: prepare_message
        run: |
          echo "Generating Slack message..."
          UPDATED_PAGES=""
          for page in $(jq -c '.pages[]' <<< "${{ toJSON(github.event) }}"); do
            PAGE_URL=$(jq -r '.html_url' <<< "$page")
            PAGE_TITLE=$(jq -r '.title' <<< "$page")
            UPDATED_PAGES="${UPDATED_PAGES}\n- [${PAGE_TITLE}](${PAGE_URL})"
          done
          echo "UPDATED_PAGES=${UPDATED_PAGES}" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "📝 The following Wiki pages were updated:",
              "attachments": [
                {
                  "title": "Updated Pages",
                  "text": "${{ env.UPDATED_PAGES }}",
                  "color": "#36a64f"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
