name: Wiki Update Notification

on:
  gollum:
    branches:
      - main

jobs:
  slack-notification:
    runs-on: macos-latest  # Platform for running the workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "📝 A Wiki page was updated!",
              "attachments": [
                {
                  "title": "Updated Wiki Pages",
                  "text": "${{ github.event.pages[*].html_url | join('\n') }}",
                  "color": "#36a64f"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

